services:
  sonarqube:
    image: sonarqube:9.9.5-community
    ports:
      - "34501:9000"
  db:
    image: mariadb:10.6.17
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: bookplace
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
    ports:
      - "34502:3306"
  prometheus:
    image: prom/prometheus:v2.51.2
    ports:
      - "34503:9090"
  grafana:
    image: grafana/grafana:10.4.2-ubuntu
    ports:
      - "34504:3000"
volumes:
  data:
